DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS visited;

CREATE TABLE user(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    character TEXT DEFAULT 'character1.svg',
    firstname TEXT NOT NULL,
    lastname TEXT NOT NULL,
    email TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL,
    verified TEXT NOT NULL DEFAULT 'false',
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE visited(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id INTEGER NOT NULL,
    fsq_id TEXT UNIQUE NOT NULL,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES user (id)
);